### ISSUE TITLE
-Xmax-classfile-name scalacOption not supported by scalac 2.13

### ISSUE THREAD

**Issue by PeterPerhac** [hmrc/sbt-settings#10]
https://github.com/hmrc/sbt-settings/blob/master/src/main/scala/uk/gov/hmrc/DefaultBuildSettings.scala#L36
This setting causes scala 2.13 compilation to fail because this option has been removed from scala 2.13.0 compiler.

> Removed -Xmax-classfile-length
> It's hard-coded to 240 now (#7497)

from: https://github.com/scala/scala/releases/tag/v2.13.0

**Comment by colin-lamed** [comment]
Resolved by #21
