### ISSUE TITLE
Difference in `sbt-git-stamp` versions between plugins.sbt and PluginBuild.scala

### ISSUE THREAD

**Issue by githubmo** [hmrc/sbt-settings#6]
It seems there is a difference between the versions of `sbt-git-stamp` in `plugins.sbt` which has version 5.1.0 and `PluginBuild.scala` which has version 5.2.0.

**Comment by agilestevesmith** [comment]
Hi @githubmo, because sbt-git-stamp uses sbt-settings itself the versions are deliberately kept separate. Thanks
